### ISSUE TITLE
Hardcoded API Version

### ISSUE THREAD

**Issue by mamichels** [Inflectra/jasmine-spiratest#1]
## Whats wrong
The module internally refers to an outdated version of the SpiraTest REST API. Using the module with an newer SpiraTest instance will result in some weird behaviour, e.g. timeouts, TCP connection errors etc. Most troublesome, the reports are still being send successfully to SpiraTest but the module does not indicate a successful transaction.

Tested with an SpiraTest Instance of V6.3.

## Minimal Fix
Indicate within the documentation that the hardcoded version is V5.0.

## Optimal Fix
Define the instance version within the config object passed to the reporters constructor.

**Comment by simonhbor** [comment]
The v5 API is not outdated and is still fully compatible with v6 of the Application. This code using the v5 API should not cause any lack of functionality. If you need support with the plugin please contact us at support@inflectra.com
